#!/usr/bin/env python3
"""The names of the hints for the C port: port/src/gen/pdnames.h (the
table programs) and port/src/gen/ddnames.h (the menu, DDPCMAIN.EXE).

    portmap.py [--check]

The port (port/) runs the table programs' code as C over the programs'
own memory image, loaded from the player's PD.EXE or PD2.EXE.  Its C
refers to variables, records and routines by their names in the hints;
this tool writes where each name is in both programs, so that one C
engine runs either:

  * per program: file size, SHA-256 (the loader checks it is the file the
    hints describe), the segments' frames;
  * PDN_NAMES(X): X(SEG, name, address in PD.EXE, address in PD2.EXE) for
    every name of either hints file, 0xFFFF where a program has none.

ddnames.h has the menu's file size, SHA-256 and frames, and
DDM_NAMES(X): X(SEG, name, offset) for every name of its hints.

Names that exist in one table program only are listed on stderr (not
with --check).  --check compares with the files instead of writing them
(exit status 1 when one is out of date).  Only addresses and a hash go into the header, no bytes of
the game.
"""
import hashlib, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
sys.path.insert(0, HERE)
from disasm import Hints, game_dir

OUT = os.path.join(ROOT, 'port', 'src', 'gen', 'pdnames.h')
OUT_MENU = os.path.join(ROOT, 'port', 'src', 'gen', 'ddnames.h')
PROGRAMS = [('PD1', 'PD.hints'), ('PD2', 'PD2.hints')]
SEGS = ['CODE', 'TDATA', 'DATA', 'XDATA', 'BSS', 'STACK']
MENU_SEGS = ['CODE', 'DATA', 'FONTS', 'OPTIONS', 'HISTORY', 'STACK']


def program_info(key, hints, segs=SEGS):
    path = os.path.join(game_dir(), hints.exe)
    data = open(path, 'rb').read()
    lines = [f'#define {key}_EXE "{hints.exe}"',
             f'#define {key}_SIZE {len(data)}u',
             f'#define {key}_SHA256 "{hashlib.sha256(data).hexdigest()}"']
    frames = {s.name: s.frame for s in hints.segs}
    for s in segs:
        lines.append(f'#define {key}_{s} 0x{frames[s]:04X}u')
    return lines


def generate_menu():
    h = Hints(os.path.join(ROOT, 'src', 'DDPCMAIN.hints'))
    out = ['/* ddnames.h - generated by tools/portmap.py from src/DDPCMAIN.hints: the',
           ' * menu program the port runs and where the names of its hints are.  No',
           ' * game data.  Do not edit: rerun the tool. */',
           '#ifndef PD_GEN_DDNAMES_H', '#define PD_GEN_DDNAMES_H', '']
    out += program_info('DDM', h, MENU_SEGS) + ['']
    names = {}
    for (seg, off), name in h.names.items():
        names[name] = (seg, off)
    for seg, off, name in h.code:
        if name:
            names.setdefault(name, (seg, off))
    out.append('/* X(SEG, name, offset), in the order of the addresses */')
    out.append('#define DDM_NAMES(X) \\')
    for n in sorted(names, key=lambda n: (MENU_SEGS.index(names[n][0]), names[n][1], n)):
        seg, off = names[n]
        out.append(f'    X({seg}, {n}, 0x{off:04X}) \\')
    out += ['', '#endif', '']
    return '\n'.join(out)


def generate(quiet=False):
    hs = [Hints(os.path.join(ROOT, 'src', f)) for _, f in PROGRAMS]
    out = ['/* pdnames.h - generated by tools/portmap.py from src/PD.hints and',
           ' * src/PD2.hints: the programs the port runs and where the names of the',
           ' * hints are in each.  No game data.  Do not edit: rerun the tool. */',
           '#ifndef PD_GEN_PDNAMES_H', '#define PD_GEN_PDNAMES_H', '']
    for (key, _), h in zip(PROGRAMS, hs):
        out += program_info(key, h) + ['']
    # name -> (seg, [addr per program]); a name keeps the segment of PD.hints
    names, seg_of = {}, {}
    for i, h in enumerate(hs):
        for (seg, off), name in h.names.items():
            if name in seg_of and seg_of[name] != seg:
                raise SystemExit(f'{name}: {seg_of[name]} in one program, {seg} in the other')
            seg_of[name] = seg
            names.setdefault(name, [None, None])[i] = off
        for seg, off, name in h.code:
            if name:
                seg_of.setdefault(name, seg)
                names.setdefault(name, [None, None])[i] = off
    only = [n for n, a in names.items() if None in a]
    for n in sorted(only if not quiet else []):
        a = names[n]
        print(f'only in {"PD2" if a[0] is None else "PD"}: {seg_of[n]}:{n}', file=sys.stderr)
    out.append('/* X(SEG, name, PD.EXE, PD2.EXE), in the order of PD.EXE\'s addresses */')
    out.append('#define PDN_NAMES(X) \\')
    order = sorted(names, key=lambda n: (SEGS.index(seg_of[n]),
                                         names[n][0] if names[n][0] is not None else 0x10000,
                                         names[n][1] or 0, n))
    for n in order:
        a = ['0x%04X' % v if v is not None else '0xFFFF' for v in names[n]]
        out.append(f'    X({seg_of[n]}, {n}, {a[0]}, {a[1]}) \\')
    out += ['', '#endif', '']
    return '\n'.join(out)


def main():
    check = '--check' in sys.argv[1:]
    outs = [(OUT, generate(quiet=check)), (OUT_MENU, generate_menu())]
    if check:
        stale = [os.path.relpath(p, ROOT) for p, text in outs
                 if (open(p, encoding='utf-8').read() if os.path.exists(p) else '') != text]
        if stale:
            print(f'{", ".join(stale)} out of date: run tools/portmap.py')
            sys.exit(1)
        print(f'{", ".join(os.path.relpath(p, ROOT) for p, _ in outs)} up to date')
        return
    for path, text in outs:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print(f'{os.path.relpath(path, ROOT)}: {text.count(chr(10) + "    X(")} names')


if __name__ == '__main__':
    main()
