#!/usr/bin/env python3
"""The names of the hints for the C port: port/src/gen/pdnames.h.

    portmap.py [--check]

The port (port/) runs the table programs' code as C over the programs'
own memory image, loaded from the player's PD.EXE or PD2.EXE.  Its C
refers to variables, records and routines by their names in the hints;
this tool writes where each name is in both programs, so that one C
engine runs either:

  * per program: file size, SHA-256 (the loader checks it is the file the
    hints describe), the segments' frames;
  * PDN_NAMES(X): X(SEG, name, address in PD.EXE, address in PD2.EXE) for
    every name of either hints file, 0xFFFF where a program has none.

Names that exist in one program only are listed on stderr (not with
--check).  --check
compares with the file instead of writing it (exit status 1 when it is
out of date).  Only addresses and a hash go into the header, no bytes of
the game.
"""
import hashlib, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..'))
sys.path.insert(0, HERE)
from disasm import Hints, game_dir

OUT = os.path.join(ROOT, 'port', 'src', 'gen', 'pdnames.h')
PROGRAMS = [('PD1', 'PD.hints'), ('PD2', 'PD2.hints')]
SEGS = ['CODE', 'TDATA', 'DATA', 'XDATA', 'BSS', 'STACK']


def program_info(key, hints):
    path = os.path.join(game_dir(), hints.exe)
    data = open(path, 'rb').read()
    lines = [f'#define {key}_EXE "{hints.exe}"',
             f'#define {key}_SIZE {len(data)}u',
             f'#define {key}_SHA256 "{hashlib.sha256(data).hexdigest()}"']
    frames = {s.name: s.frame for s in hints.segs}
    for s in SEGS:
        lines.append(f'#define {key}_{s} 0x{frames[s]:04X}u')
    return lines


def generate(quiet=False):
    hs = [Hints(os.path.join(ROOT, 'src', f)) for _, f in PROGRAMS]
    out = ['/* pdnames.h - generated by tools/portmap.py from src/PD.hints and',
           ' * src/PD2.hints: the programs the port runs and where the names of the',
           ' * hints are in each.  No game data.  Do not edit: rerun the tool. */',
           '#ifndef PD_GEN_PDNAMES_H', '#define PD_GEN_PDNAMES_H', '']
    for (key, _), h in zip(PROGRAMS, hs):
        out += program_info(key, h) + ['']
    # name -> (seg, [addr per program]); a name keeps the segment of PD.hints
    names, seg_of = {}, {}
    for i, h in enumerate(hs):
        for (seg, off), name in h.names.items():
            if name in seg_of and seg_of[name] != seg:
                raise SystemExit(f'{name}: {seg_of[name]} in one program, {seg} in the other')
            seg_of[name] = seg
            names.setdefault(name, [None, None])[i] = off
        for seg, off, name in h.code:
            if name:
                seg_of.setdefault(name, seg)
                names.setdefault(name, [None, None])[i] = off
    only = [n for n, a in names.items() if None in a]
    for n in sorted(only if not quiet else []):
        a = names[n]
        print(f'only in {"PD2" if a[0] is None else "PD"}: {seg_of[n]}:{n}', file=sys.stderr)
    out.append('/* X(SEG, name, PD.EXE, PD2.EXE), in the order of PD.EXE\'s addresses */')
    out.append('#define PDN_NAMES(X) \\')
    order = sorted(names, key=lambda n: (SEGS.index(seg_of[n]),
                                         names[n][0] if names[n][0] is not None else 0x10000,
                                         names[n][1] or 0, n))
    for n in order:
        a = ['0x%04X' % v if v is not None else '0xFFFF' for v in names[n]]
        out.append(f'    X({seg_of[n]}, {n}, {a[0]}, {a[1]}) \\')
    out += ['', '#endif', '']
    return '\n'.join(out)


def main():
    check = '--check' in sys.argv[1:]
    text = generate(quiet=check)
    if check:
        old = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if old != text:
            print(f'{os.path.relpath(OUT, ROOT)} is out of date: run tools/portmap.py')
            sys.exit(1)
        print(f'{os.path.relpath(OUT, ROOT)} up to date')
        return
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print(f'{os.path.relpath(OUT, ROOT)}: {text.count(chr(10) + "    X(")} names')


if __name__ == '__main__':
    main()
